//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
		public class PushArgs
		{
		public Vector3 point;
		public float pushLvl;
				public PushArgs (Vector2 point, float pushLvl)
				{
			this.point = point;
			this.pushLvl = pushLvl;
				}
		}
}

